version: '3'

services:
  postgres:
    image: postgres:14.4-alpine3.16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    expose:
      - 5432
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8001:8080

  nginx:
    image: nginx
    container_name: nginx
    build:
        context: ./nignx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/crawler_ui/build:/app
    ports:
      - "8080:80"
    environment:
      NGINX_PORT: "80"
      NGINX_RESPONSE: "'Hi! It is NGINX!'"
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    # depends_on:
    #   - crawler-service
    restart: always

  crawler-service:
    image: crawler-service
    container_name: crawler-service
    build:
      context: ./crawler_service
      target: crawler_service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      SECRET_KEY: ${SECRET_KEY}
    restart: always
    ports:
      - "8000:8000"
    # TODO
    #command: gunicorn crawler.asgi:application  -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker
    command: python /visible/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
      # - migration
    # TODO
    volumes:
      - ./crawler_service/crawler:/visible/crawler
  
  # migration:
  #   image: crawler-service
  #   command: python /visible/manage.py migrate --noinput
  #   volumes:
  #     - ./crawler_service/crawler:/visible/crawler
  #   depends_on:
  #     - postgres
