# Generated by Django 4.0.5 on 2022-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=8192)),
                ('status', models.CharField(choices=[('s', 'SUBMITTED'), ('i', 'IN_PROGRESS'), ('d', 'DONE'), ('e', 'ERROR')], max_length=1)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
