FROM nginx

WORKDIR /app

RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash \
    && apt-get install nodejs -yq

COPY ./crawler_ui ./

RUN npm install
RUN npm run build